services:
  postgres:
    image: postgres:16-alpine
    container_name: blog-postgres
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: tenno
      POSTGRES_PASSWORD: vor_speaks_truth
    ports:
      - "5432:5432"
    volumes:
      - blog_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  blog_pgdata:
